name: Lighthouse CI

on:
  push:
    branches:
      - '*' # Запускать для всех веток
  pull_request:
    branches:
      - '*' # Запускать для всех PR

jobs:
  lighthouse-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run Lighthouse CI
        run: lhci autorun --config .lighthouserc.json

      - name: Verify results directory
        run: |
          ls -la ./lighthouse-results
          echo "Files count: $(ls ./lighthouse-results | wc -l)"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-results
          path: ./lighthouse-results/
