name: Lighthouse CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  lighthouse-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # LTS-версия
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli

      - name: Verify LHCI installation
        run: |
          echo "LHCI path: $(which lhci)"
          lhci --version

      - name: Run Lighthouse CI
        run: lhci autorun --config .lighthouserc.json

      - name: Upload results
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-results
          path: ./lighthouse-results/
